### PR TITLE
ProgressRoadRunner

### PR DESCRIPTION
**Pull request by yayaa**
Hey,

I just created a progress implementation of your great library. I am not sure if the way i did, was correct way to do it though. But as i follow up your code i managed it, so take a look at it please. And if you can implement this option to other RoadRunner types as well, that would be actually great. Maybe you can create much more generic way then i did, i just needed this implementation so i modified it quickly.

### CODE REVIEW

**Comment by yayaa** [comment]
I also implemented programmatically creation of the view with Builder, but it can be optimise and make it more generic though.

**Comment by yayaa** [comment]
I just realised that it's been almost a year for this PR. I updated a bit, and fix Travis for you.
Please feel free to take a look and merge. @glomadrian

**Comment by yayaa** [comment]
what_now

**Comment by yayaa** [comment]
Ok, suit yourself :)

**Comment by glomadrian** [comment]
Sorry for my lake of care about this PR i will check as son as possible

**Comment by glomadrian** [comment]
Thanks for you contribution @yayaa

**Pull request merged**
